print('x: ',end='')
x = int(input())
print('y: ',end='')
y = int(input())
print("두 수의 합: ",x+y)
print("두 수의 차: ",x-y)
print("두 수의 곱: ",x*y)
print("두 수의 평균: ",(x+y)/2.0)
print("큰 수: ",max(x,y))
print("작은 수: ",min(x,y))